/*
 * Generated by lists-generator.kts
 */

package com.anatawa12.protobuf;

import java.util.Objects;

@FunctionalInterface
public interface BooleanUnaryOperator {
    boolean applyAsBoolean(boolean operand);

    default BooleanUnaryOperator compose(BooleanUnaryOperator before) {
        Objects.requireNonNull(before);
        return (boolean v) -> applyAsBoolean(before.applyAsBoolean(v));
    }

    default BooleanUnaryOperator andThen(BooleanUnaryOperator after) {
        Objects.requireNonNull(after);
        return (boolean t) -> after.applyAsBoolean(applyAsBoolean(t));
    }

    static BooleanUnaryOperator identity() {
        return t -> t;
    }
}