/*
 * Generated by lists-generator.kts
 */

package com.anatawa12.protobuf;

import java.lang.reflect.Array;
import java.util.AbstractList;
import java.util.Arrays;
import java.util.Collection;
import java.util.ConcurrentModificationException;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.RandomAccess;

public class BooleanList extends AbstractList<Boolean> implements List<Boolean>, RandomAccess {
    protected int size;
    protected boolean[] backed;

    public BooleanList() {
        this(10, 1);
    }

    public BooleanList(int capacity) {
        this(capacity == 0 ? 1 : capacity, 0);
    }

    public BooleanList(BooleanList from) {
        this(from.size());
        addAll(from);
    }

    // internal: in this constructor, empty backed array is allowed
    // but it may cause infinity loop or index out of exeption on adding value.
    BooleanList(int capacity, int marker) {
        this.backed = new boolean[capacity];
    }

    // Query Operations

    @Override
    public final int size() {
        return size;
    }

    @Override
    public final boolean isEmpty() {
        return size == 0;
    }

    public final boolean contains(boolean element) {
        for (boolean value : backed) {
            if (value == element)
                return true;
        }
        return false;
    }

    /**
     * You should use {@link BooleanList#contains(boolean)}
     */
    @Deprecated
    @Override
    public final boolean contains(Object o) {
        if (!(o instanceof Boolean)) return false;
        return contains((boolean) o);
    }

    @Override
    public final BooleanIterator iterator() {
        return new ListIterator(0);
    }

    @Override
    public final Object[] toArray() {
        return toArray(new Object[0]);
    }

    @SuppressWarnings("unchecked")
    @Override
    public final <T> T[] toArray(T[] a) {
        // create new array if size is not enough
        if (a.length < size) a = (T[]) Array.newInstance(a.getClass().getComponentType(), size);
        for (int i = 0; i < size; i++) {
            a[i] = (T) (Boolean) backed[i];
        }
        return a;
    }

    public final boolean[] toBooleanArray() {
        return Arrays.copyOf(backed, size);
    }

    // Modification Operations

    public boolean add(boolean value) {
        add(size(), value);
        return true;
    }

    /**
     * You should use {@link BooleanList#add(boolean)}
     */
    @Deprecated
    @Override
    public final boolean add(Boolean boxed) {
        return add((boolean) boxed);
    }

    /**
     * You should use {@link BooleanList#removeBoolean(boolean)}
     */
    @Deprecated
    @Override
    public final boolean remove(Object o) {
        if (!(o instanceof Boolean))
            return false;
        return removeBoolean((boolean) o);
    }

    public boolean removeBoolean(boolean value) {
        int i = indexOf(value);
        if (i < 0) return false;
        removeAt(i);
        return true;
    }

    // Bulk Modification Operations

    @Override
    public final boolean containsAll(Collection<?> c) {
        java.util.Iterator<?> iter = c.iterator();
        if (iter instanceof BooleanIterator) {
            BooleanIterator ofBoolean = (BooleanIterator) iter;
            while (ofBoolean.hasNext())
                if (!contains(ofBoolean.nextBoolean()))
                    return false;
        } else {
            while (iter.hasNext())
                if (!contains(iter.next()))
                    return false;
        }
        return true;
    }

    public boolean addAll(boolean[] c) {
        return addAll(size, c, c.length);
    }

    public boolean addAll(int index, boolean[] c) {
        return addAll(index, c, c.length);
    }

    @Override
    public boolean addAll(Collection<? extends Boolean> c) {
        if (c == this) throw new IllegalArgumentException("can't addAll this itself");
        if (c instanceof BooleanList)
            return addAll(size, ((BooleanList) c).backed, ((BooleanList) c).size);
        return addAll(size, toPrimitives(c));
    }

    @Override
    public boolean addAll(int index, Collection<? extends Boolean> c) {
        if (c == this) throw new IllegalArgumentException("can't addAll this itself");
        if (c instanceof BooleanList)
            return addAll(index, ((BooleanList) c).backed, ((BooleanList) c).size);
        return addAll(index, toPrimitives(c));
    }

    private boolean addAll(int index, boolean[] c, int addSize) {
        rangeCheckForAdd(index);
        modCount++;
        if (addSize == 0) return false;
        boolean[] ary;
        if (backed.length < size + addSize) {
            int newSize = backed.length * 2;
            while (newSize < size + addSize) newSize *= 2;
            ary = new boolean[newSize];
            // copy 0..<index
            System.arraycopy(backed, 0,
                    ary, 0, index);
            backed = ary;
        } else {
            ary = backed;
            // no resize
        }
        // copy index..<size to index+addSize..<size+addSize
        System.arraycopy(backed, index,
                ary, index + addSize, size - index);
        // copy 0..<addSize to index..<index+addSize
        System.arraycopy(c, 0,
                ary, index, addSize);
        size += addSize;
        return true;
    }

    @Override
    public boolean removeAll(Collection<?> c) {
        return batchRemove(c, true);
    }

    @Override
    public boolean retainAll(Collection<?> c) {
        return batchRemove(c, false);
    }

    private boolean batchRemove(Collection<?> c, boolean complement) {
        final boolean[] data = this.backed;
        int r = 0;
        int w = 0;
        boolean modified = false;
        try {
            if (c instanceof BooleanList) {
                BooleanList intList = (BooleanList) c;
                for (; r < size; r++)
                    if (intList.contains(data[r]) == complement)
                        data[w++] = data[r];
            } else {
                for (; r < size; r++)
                    if (c.contains(data[r]) == complement)
                        data[w++] = data[r];
            }
        } finally {
            // Preserve behavioral compatibility with AbstractCollection,
            // even if c.contains() throws.
            if (r != size) {
                System.arraycopy(data, r,
                        data, w,
                        size - r);
                w += size - r;
            }
            if (w != size) {
                size = w;
                modified = true;
            }
        }
        return modified;
    }

    public final void replaceAll(BooleanUnaryOperator operator) {
        Objects.requireNonNull(operator);
        final ListIterator li = this.listIterator();
        while (li.hasNext()) {
            li.set(operator.applyAsBoolean(li.nextBoolean()));
        }
    }

    @Override
    public void clear() {
        size = 0;
    }

    public final boolean equals(Object o) {
        if (o == this) return true;
        if (!(o instanceof List<?>)) return false;
        if (o instanceof BooleanList) {
            if (((BooleanList) o).size != size) return false;

            ListIterator e1 = listIterator();
            ListIterator e2 = ((BooleanList) o).listIterator();
            while (e1.hasNext() && e2.hasNext()) {
                if (e1.nextBoolean() != e2.nextBoolean())
                    return false;
            }
            return !(e1.hasNext() || e2.hasNext());
        }

        ListIterator e1 = listIterator();
        java.util.ListIterator<?> e2 = ((List<?>) o).listIterator();
        while (e1.hasNext() && e2.hasNext()) {
            boolean o1 = e1.nextBoolean();
            Object o2 = e2.next();
            if (!eq(o1, o2))
                return false;
        }
        return !(e1.hasNext() || e2.hasNext());
    }

    @Override
    public final int hashCode() {
        int hashCode = 1;
        final ListIterator li = this.listIterator();
        while (li.hasNext())
            hashCode = 31 * hashCode + Boolean.hashCode(li.nextBoolean());
        return hashCode;
    }

    // Positional Access Operations

    public final boolean getBoolean(int index) {
        rangeCheck(index);
        return backed[index];
    }

    /**
     * You should use {@link BooleanList#getBoolean getBoolean}
     */
    @Deprecated
    @Override
    public final Boolean get(int index) {
        return getBoolean(index);
    }

    public boolean set(int index, boolean element) {
        rangeCheck(index);
        boolean r = backed[index];
        backed[index] = element;
        return r;
    }

    /**
     * You should use {@link BooleanList#set(int, boolean)}
     */
    @Deprecated
    @Override
    public final Boolean set(int index, Boolean element) {
        return set(index, (boolean) element);
    }

    public void add(int index, boolean value) {
        rangeCheckForAdd(index);
        modCount++;
        boolean[] ary;
        if (backed.length < size + 1) {
            ary = new boolean[backed.length * 2];
            // copy 0..<index
            System.arraycopy(backed, 0,
                    ary, 0, index);
            backed = ary;
        } else {
            ary = backed;
            // no resize
        }
        // copy index..<size to index+1..<size+1
        System.arraycopy(backed, index,
                ary, index + 1, size - index);
        ary[index] = value;
        size++;
    }

    /**
     * You should use {@link BooleanList#add(int, boolean)}
     */
    @Deprecated
    @Override
    public void add(int index, Boolean element) {
        add(index, (boolean) element);
    }

    public boolean removeAt(int index) {
        rangeCheck(index);
        modCount++;
        boolean r = backed[index];
        // copy index+1..<size to index..<size-1
        System.arraycopy(backed, index + 1,
                backed, index, size - index - 1);
        size--;
        return r;
    }

    /**
     * You should use {@link BooleanList#removeAt removeAt}
     */
    @Deprecated
    @Override
    public Boolean remove(int index) {
        return removeAt(index);
    }

    /**
     * You should use {@link BooleanList#indexOf(boolean)}
     */
    @Override
    public final int indexOf(Object o) {
        if (!(o instanceof Boolean)) return -1;
        return indexOf((boolean) o);
    }

    public final int indexOf(boolean value) {
        for (int i = 0; i < size; i++) {
            if (value == backed[i]) return i;
        }
        return -1;
    }

    /**
     * You should use {@link BooleanList#lastIndexOf(boolean)}
     */
    @Override
    public final int lastIndexOf(Object o) {
        if (!(o instanceof Boolean)) return -1;
        return lastIndexOf((boolean) o);
    }

    public final int lastIndexOf(boolean value) {
        for (int i = size - 1; i >= 0; i--) {
            if (value == backed[i]) return i;
        }
        return -1;
    }

    // List Iterators

    @Override
    public final ListIterator listIterator() {
        return new ListIterator(0);
    }

    @Override
    public final ListIterator listIterator(int index) {
        rangeCheckForAdd(index);
        return new ListIterator(index);
    }

    public final class ListIterator implements BooleanIterator, java.util.ListIterator<Boolean> {
        int expectedModCount = modCount;
        int lastRet = -1;
        int cursor;

        public ListIterator(int cursor) {
            this.cursor = cursor;
        }

        @Override
        public boolean hasNext() {
            return cursor < size;
        }

        @Override
        public boolean nextBoolean() {
            try {
                checkForComodification();
                int i = cursor;
                boolean next = getBoolean(i);
                lastRet = i;
                cursor = i + 1;
                return next;
            } catch (IndexOutOfBoundsException e) {
                checkForComodification();
                throw new NoSuchElementException();
            }
        }

        @Override
        public Boolean next() {
            return BooleanIterator.super.next();
        }

        public void remove() {
            if (lastRet < 0)
                throw new IllegalStateException();
            checkForComodification();

            try {
                BooleanList.this.removeAt(lastRet);
                if (lastRet < cursor)
                    cursor--;
                lastRet = -1;
                expectedModCount = modCount;
            } catch (IndexOutOfBoundsException e) {
                throw new ConcurrentModificationException();
            }
        }

        public boolean hasPrevious() {
            return cursor != 0;
        }

        public boolean previousBoolean() {
            checkForComodification();
            try {
                int i = cursor - 1;
                boolean previous = getBoolean(i);
                lastRet = cursor = i;
                return previous;
            } catch (IndexOutOfBoundsException e) {
                checkForComodification();
                throw new NoSuchElementException();
            }
        }

        public int nextIndex() {
            return cursor;
        }

        public int previousIndex() {
            return cursor - 1;
        }

        public void set(boolean e) {
            if (lastRet < 0)
                throw new IllegalStateException();
            checkForComodification();

            try {
                BooleanList.this.set(lastRet, e);
                expectedModCount = modCount;
            } catch (IndexOutOfBoundsException ex) {
                throw new ConcurrentModificationException();
            }
        }

        public void add(boolean e) {
            checkForComodification();

            try {
                int i = cursor;
                BooleanList.this.add(i, e);
                lastRet = -1;
                cursor = i + 1;
                expectedModCount = modCount;
            } catch (IndexOutOfBoundsException ex) {
                throw new ConcurrentModificationException();
            }
        }

        public void set(Boolean e) {
            set((boolean) e);
        }

        public void add(Boolean e) {
            add((boolean) e);
        }

        public Boolean previous() {
            return previousBoolean();
        }

        private void checkForComodification() {
            if (modCount != expectedModCount)
                throw new ConcurrentModificationException();
        }
    }

    //////////////////////

    private boolean[] toPrimitives(Collection<? extends Boolean> c) {
        Boolean[] wrapper = c.toArray(EMPTY_WRAPPER_ARRAY);
        if (wrapper.length == 0) return EMPTY_PRIMITIVE_ARRAY;
        boolean[] primitives = new boolean[wrapper.length];
        for (int i = 0; i < primitives.length; i++) {
            primitives[i] = wrapper[i];
        }
        return primitives;
    }

    private void rangeCheck(int index) {
        if (index < 0 || index >= size())
            throw new IndexOutOfBoundsException(outOfBoundsMsg(index));
    }

    private void rangeCheckForAdd(int index) {
        if (index < 0 || index > size())
            throw new IndexOutOfBoundsException(outOfBoundsMsg(index));
    }

    private String outOfBoundsMsg(int index) {
        return "Index: " + index + ", Size: " + size();
    }

    private boolean eq(boolean o1, Object o2) {
        return o2 instanceof Boolean && o1 == (boolean) o2;
    }

    private static final Boolean[] EMPTY_WRAPPER_ARRAY = new Boolean[0];
    private static final boolean[] EMPTY_PRIMITIVE_ARRAY = new boolean[0];
}
