/*
 * Generated by lists-generator.kts
 */

package com.anatawa12.protobuf;

import java.lang.reflect.Array;
import java.util.AbstractList;
import java.util.Arrays;
import java.util.Collection;
import java.util.ConcurrentModificationException;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.PrimitiveIterator;
import java.util.RandomAccess;
import java.util.function.DoubleUnaryOperator;

public class DoubleList extends AbstractList<Double> implements List<Double>, RandomAccess {
    protected int size;
    protected double[] backed;

    public DoubleList() {
        this(10, 1);
    }

    public DoubleList(int capacity) {
        this(capacity == 0 ? 1 : capacity, 0);
    }

    public DoubleList(DoubleList from) {
        this(from.size());
        addAll(from);
    }

    // internal: in this constructor, empty backed array is allowed 
    // but it may cause infinity loop or index out of exeption on adding value.
    DoubleList(int capacity, int marker) {
        this.backed = new double[capacity];
    }

    // Query Operations

    @Override
    public final int size() {
        return size;
    }

    @Override
    public final boolean isEmpty() {
        return size == 0;
    }

    public final boolean contains(double element) {
        for (double value : backed) {
            if (value == element)
                return true;
        }
        return false;
    }

    /**
     * You should use {@link DoubleList#contains(double)}
     */
    @Deprecated
    @Override
    public final boolean contains(Object o) {
        if (!(o instanceof Double)) return false;
        return contains((double)o);
    }

    @Override
    public final PrimitiveIterator.OfDouble iterator() {
        return new ListIterator(0);
    }

    @Override
    public final Object[] toArray() {
        return toArray(new Object[0]);
    }

    @SuppressWarnings("unchecked")
    @Override
    public final <T> T[] toArray(T[] a) {
        // create new array if size is not enough
        if (a.length < size) a = (T[]) Array.newInstance(a.getClass().getComponentType(), size);
        for (int i = 0; i < size; i++) {
            a[i] = (T)(Double)backed[i];
        }
        return a;
    }

    public final double[] toDoubleArray() {
        return Arrays.copyOf(backed, size);
    }

    // Modification Operations

    public boolean add(double value) {
        add(size(), value);
        return true;
    }

    /**
     * You should use {@link DoubleList#add(double)}
     */
    @Deprecated
    @Override
    public final boolean add(Double boxed) {
        return add((double)boxed);
    }

    /**
     * You should use {@link DoubleList#removeDouble(double)}
     */
    @Deprecated
    @Override
    public final boolean remove(Object o) {
        if (!(o instanceof Double))
            return false;
        return removeDouble((double)o);
    }

    public boolean removeDouble(double value) {
        int i = indexOf(value);
        if (i < 0) return false;
        removeAt(i);
        return true;
    }

    // Bulk Modification Operations

    @Override
    public final boolean containsAll(Collection<?> c) {
        java.util.Iterator<?> iter = c.iterator();
        if (iter instanceof PrimitiveIterator.OfDouble) {
            PrimitiveIterator.OfDouble ofDouble = (PrimitiveIterator.OfDouble) iter;
            while (ofDouble.hasNext())
                if (!contains(ofDouble.nextDouble()))
                    return false;
        } else {
            while (iter.hasNext())
                if (!contains(iter.next()))
                    return false;
        }
        return true;
    }

    public boolean addAll(double[] c) {
        return addAll(size, c, c.length);
    }

    public boolean addAll(int index, double[] c) {
        return addAll(index, c, c.length);
    }

    @Override
    public boolean addAll(Collection<? extends Double> c) {
        if (c == this) throw new IllegalArgumentException("can't addAll this itself");
        if (c instanceof DoubleList)
            addAll(size, ((DoubleList) c).backed, ((DoubleList) c).size);
        return addAll(size, toPrimitives(c));
    }

    @Override
    public boolean addAll(int index, Collection<? extends Double> c) {
        if (c == this) throw new IllegalArgumentException("can't addAll this itself");
        if (c instanceof DoubleList)
            addAll(index, ((DoubleList) c).backed, ((DoubleList) c).size);
        return addAll(index, toPrimitives(c));
    }

    private boolean addAll(int index, double[] c, int addSize) {
        rangeCheckForAdd(index);
        modCount++;
        if (size == 0) return false;
        double[] ary;
        if (backed.length < size + addSize) {
            int newSize = backed.length * 2;
            while (newSize < size + addSize) newSize *= 2;
            ary = new double[newSize];
            // copy 0..<index
            System.arraycopy(backed, 0,
                    ary, 0, index);
            backed = ary;
        } else {
            ary = backed;
            // no resize
        }
        // copy index..<size to index+addSize..<size+addSize
        System.arraycopy(backed, index,
                ary, index + addSize, size - index);
        // copy 0..<addSize to index..<index+addSize
        System.arraycopy(c, 0,
                ary, index, addSize);
        size += addSize;
        return true;
    }

    @Override
    public boolean removeAll(Collection<?> c) {
        return batchRemove(c, true);
    }

    @Override
    public boolean retainAll(Collection<?> c) {
        return batchRemove(c, false);
    }

    private boolean batchRemove(Collection<?> c, boolean complement) {
        final double[] data = this.backed;
        int r = 0;
        int w = 0;
        boolean modified = false;
        try {
            if (c instanceof DoubleList) {
                DoubleList intList = (DoubleList) c;
                for (; r < size; r++)
                    if (intList.contains(data[r]) == complement)
                        data[w++] = data[r];
            } else {
                for (; r < size; r++)
                    if (c.contains(data[r]) == complement)
                        data[w++] = data[r];
            }
        } finally {
            // Preserve behavioral compatibility with AbstractCollection,
            // even if c.contains() throws.
            if (r != size) {
                System.arraycopy(data, r,
                        data, w,
                        size - r);
                w += size - r;
            }
            if (w != size) {
                size = w;
                modified = true;
            }
        }
        return modified;
    }

    public final void replaceAll(DoubleUnaryOperator operator) {
        Objects.requireNonNull(operator);
        final ListIterator li = this.listIterator();
        while (li.hasNext()) {
            li.set(operator.applyAsDouble(li.nextDouble()));
        }
    }

    @Override
    public void clear() {
        size = 0;
    }

    public final boolean equals(Object o) {
        if (o == this) return true;
        if (!(o instanceof List<?>)) return false;
        if (o instanceof DoubleList) {
            if (((DoubleList) o).size != size) return false;

            ListIterator e1 = listIterator();
            ListIterator e2 = ((DoubleList) o).listIterator();
            while (e1.hasNext() && e2.hasNext()) {
                if (e1.nextDouble() != e2.nextDouble())
                    return false;
            }
            return !(e1.hasNext() || e2.hasNext());
        }

        ListIterator e1 = listIterator();
        java.util.ListIterator<?> e2 = ((List<?>) o).listIterator();
        while (e1.hasNext() && e2.hasNext()) {
            double o1 = e1.nextDouble();
            Object o2 = e2.next();
            if (!eq(o1, o2))
                return false;
        }
        return !(e1.hasNext() || e2.hasNext());
    }

    @Override
    public final int hashCode() {
        int hashCode = 1;
        final ListIterator li = this.listIterator();
        while (li.hasNext())
            hashCode = 31 * hashCode + Double.hashCode(li.nextDouble());
        return hashCode;
    }

    // Positional Access Operations

    public final double getDouble(int index) {
        rangeCheck(index);
        return backed[index];
    }

    /**
     * You should use {@link DoubleList#getDouble getDouble}
     */
    @Deprecated
    @Override
    public final Double get(int index) {
        return getDouble(index);
    }

    public double set(int index, double element) {
        rangeCheck(index);
        double r = backed[index];
        backed[index] = element;
        return r;
    }

    /**
     * You should use {@link DoubleList#set(int, double)}
     */
    @Deprecated
    @Override
    public final Double set(int index, Double element) {
        return set(index, (double)element);
    }

    public void add(int index, double value) {
        rangeCheckForAdd(index);
        modCount++;
        double[] ary;
        if (backed.length < size + 1) {
            ary = new double[backed.length * 2];
            // copy 0..<index
            System.arraycopy(backed, 0,
                    ary, 0, index);
            backed = ary;
        } else {
            ary = backed;
            // no resize
        }
        // copy index..<size to index+1..<size+1
        System.arraycopy(backed, index,
                ary, index + 1, size - index);
        ary[index] = value;
        size++;
    }

    /**
     * You should use {@link DoubleList#add(int, double)}
     */
    @Deprecated
    @Override
    public void add(int index, Double element) {
        add(index, (double)element);
    }

    public double removeAt(int index) {
        rangeCheck(index);
        modCount++;
        double r = backed[index];
        // copy index+1..<size to index..<size-1
        System.arraycopy(backed, index + 1,
                backed, index, size - index - 1);
        size--;
        return r;
    }

    /**
     * You should use {@link DoubleList#removeAt removeAt}
     */
    @Deprecated
    @Override
    public Double remove(int index) {
        return removeAt(index);
    }

    /**
     * You should use {@link DoubleList#indexOf(double)}
     */
    @Override
    public final int indexOf(Object o) {
        if (!(o instanceof Double)) return -1;
        return indexOf((double)o);
    }

    public final int indexOf(double value) {
        for (int i = 0; i < size; i++) {
            if (value == backed[i]) return i;
        }
        return -1;
    }

    /**
     * You should use {@link DoubleList#lastIndexOf(double)}
     */
    @Override
    public final int lastIndexOf(Object o) {
        if (!(o instanceof Double)) return -1;
        return indexOf((double)o);
    }

    public final int lastIndexOf(double value) {
        for (int i = size - 1; i >= 0; i--) {
            if (value == backed[i]) return i;
        }
        return -1;
    }

    // List Iterators

    @Override
    public final ListIterator listIterator() {
        return new ListIterator(0);
    }

    @Override
    public final ListIterator listIterator(int index) {
        rangeCheckForAdd(index);
        return new ListIterator(index);
    }

    public final class ListIterator implements PrimitiveIterator.OfDouble, java.util.ListIterator<Double> {
        int expectedModCount = modCount;
        int lastRet = -1;
        int cursor;

        public ListIterator(int cursor) {
            this.cursor = cursor;
        }

        @Override
        public boolean hasNext() {
            return cursor < size;
        }

        @Override
        public double nextDouble() {
            try {
                checkForComodification();
                int i = cursor;
                double next = getDouble(i);
                lastRet = i;
                cursor = i + 1;
                return next;
            } catch (IndexOutOfBoundsException e) {
                checkForComodification();
                throw new NoSuchElementException();
            }
        }

        @Override
        public Double next() {
            return PrimitiveIterator.OfDouble.super.next();
        }

        public void remove() {
            if (lastRet < 0)
                throw new IllegalStateException();
            checkForComodification();

            try {
                DoubleList.this.removeAt(lastRet);
                if (lastRet < cursor)
                    cursor--;
                lastRet = -1;
                expectedModCount = modCount;
            } catch (IndexOutOfBoundsException e) {
                throw new ConcurrentModificationException();
            }
        }

        public boolean hasPrevious() {
            return cursor != 0;
        }

        public double previousDouble() {
            checkForComodification();
            try {
                int i = cursor - 1;
                double previous = getDouble(i);
                lastRet = cursor = i;
                return previous;
            } catch (IndexOutOfBoundsException e) {
                checkForComodification();
                throw new NoSuchElementException();
            }
        }

        public int nextIndex() {
            return cursor;
        }

        public int previousIndex() {
            return cursor-1;
        }

        public void set(double e) {
            if (lastRet < 0)
                throw new IllegalStateException();
            checkForComodification();

            try {
                DoubleList.this.set(lastRet, e);
                expectedModCount = modCount;
            } catch (IndexOutOfBoundsException ex) {
                throw new ConcurrentModificationException();
            }
        }

        public void add(double e) {
            checkForComodification();

            try {
                int i = cursor;
                DoubleList.this.add(i, e);
                lastRet = -1;
                cursor = i + 1;
                expectedModCount = modCount;
            } catch (IndexOutOfBoundsException ex) {
                throw new ConcurrentModificationException();
            }
        }

        public void set(Double e) {
            set((double)e);
        }
        public void add(Double e) {
            add((double)e);
        }

        public Double previous() {
            return previousDouble();
        }

        private void checkForComodification() {
            if (modCount != expectedModCount)
                throw new ConcurrentModificationException();
        }
    }

    //////////////////////

    private double[] toPrimitives(Collection<? extends Double> c) {
        Double[] wrapper = c.toArray(EMPTY_WRAPPER_ARRAY);
        if (wrapper.length == 0) return EMPTY_PRIMITIVE_ARRAY;
        double[] primitives = new double[wrapper.length];
        for (int i = 0; i < primitives.length; i++) {
            primitives[i] = wrapper[i];
        }
        return primitives;
    }

    private void rangeCheck(int index) {
        if (index < 0 || index >= size())
            throw new IndexOutOfBoundsException(outOfBoundsMsg(index));
    }

    private void rangeCheckForAdd(int index) {
        if (index < 0 || index > size())
            throw new IndexOutOfBoundsException(outOfBoundsMsg(index));
    }

    private String outOfBoundsMsg(int index) {
        return "Index: "+index+", Size: "+size();
    }

    private boolean eq(double o1, Object o2) {
        return o2 instanceof Double && o1 == (double)o2;
    }

    private static final Double[] EMPTY_WRAPPER_ARRAY = new Double[0];
    private static final double[] EMPTY_PRIMITIVE_ARRAY = new double[0];
}
