/*
 * Generated by lists-generator.kts
 */

package com.anatawa12.protobuf;

import java.lang.reflect.Array;
import java.util.AbstractList;
import java.util.Arrays;
import java.util.Collection;
import java.util.ConcurrentModificationException;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.PrimitiveIterator;
import java.util.RandomAccess;

public class FloatList extends AbstractList<Float> implements List<Float>, RandomAccess {
    protected int size;
    protected float[] backed;

    public FloatList() {
        this(10, 1);
    }

    public FloatList(int capacity) {
        this(capacity == 0 ? 1 : capacity, 0);
    }

    public FloatList(FloatList from) {
        this(from.size());
        addAll(from);
    }

    // internal: in this constructor, empty backed array is allowed 
    // but it may cause infinity loop or index out of exeption on adding value.
    FloatList(int capacity, int marker) {
        this.backed = new float[capacity];
    }

    // Query Operations

    @Override
    public final int size() {
        return size;
    }

    @Override
    public final boolean isEmpty() {
        return size == 0;
    }

    public final boolean contains(float element) {
        for (float value : backed) {
            if (value == element)
                return true;
        }
        return false;
    }

    /**
     * You should use {@link FloatList#contains(float)}
     */
    @Deprecated
    @Override
    public final boolean contains(Object o) {
        if (!(o instanceof Float)) return false;
        return contains((float)o);
    }

    @Override
    public final FloatIterator iterator() {
        return new ListIterator(0);
    }

    @Override
    public final Object[] toArray() {
        return toArray(new Object[0]);
    }

    @SuppressWarnings("unchecked")
    @Override
    public final <T> T[] toArray(T[] a) {
        // create new array if size is not enough
        if (a.length < size) a = (T[]) Array.newInstance(a.getClass().getComponentType(), size);
        for (int i = 0; i < size; i++) {
            a[i] = (T)(Float)backed[i];
        }
        return a;
    }

    public final float[] toFloatArray() {
        return Arrays.copyOf(backed, size);
    }

    // Modification Operations

    public boolean add(float value) {
        add(size(), value);
        return true;
    }

    /**
     * You should use {@link FloatList#add(float)}
     */
    @Deprecated
    @Override
    public final boolean add(Float boxed) {
        return add((float)boxed);
    }

    /**
     * You should use {@link FloatList#removeFloat(float)}
     */
    @Deprecated
    @Override
    public final boolean remove(Object o) {
        if (!(o instanceof Float))
            return false;
        return removeFloat((float)o);
    }

    public boolean removeFloat(float value) {
        int i = indexOf(value);
        if (i < 0) return false;
        removeAt(i);
        return true;
    }

    // Bulk Modification Operations

    @Override
    public final boolean containsAll(Collection<?> c) {
        java.util.Iterator<?> iter = c.iterator();
        if (iter instanceof FloatIterator) {
            FloatIterator ofFloat = (FloatIterator) iter;
            while (ofFloat.hasNext())
                if (!contains(ofFloat.nextFloat()))
                    return false;
        } else {
            while (iter.hasNext())
                if (!contains(iter.next()))
                    return false;
        }
        return true;
    }

    public boolean addAll(float[] c) {
        return addAll(size, c, c.length);
    }

    public boolean addAll(int index, float[] c) {
        return addAll(index, c, c.length);
    }

    @Override
    public boolean addAll(Collection<? extends Float> c) {
        if (c == this) throw new IllegalArgumentException("can't addAll this itself");
        if (c instanceof FloatList)
            return addAll(size, ((FloatList) c).backed, ((FloatList) c).size);
        return addAll(size, toPrimitives(c));
    }

    @Override
    public boolean addAll(int index, Collection<? extends Float> c) {
        if (c == this) throw new IllegalArgumentException("can't addAll this itself");
        if (c instanceof FloatList)
            return addAll(index, ((FloatList) c).backed, ((FloatList) c).size);
        return addAll(index, toPrimitives(c));
    }

    private boolean addAll(int index, float[] c, int addSize) {
        rangeCheckForAdd(index);
        modCount++;
        if (addSize == 0) return false;
        float[] ary;
        if (backed.length < size + addSize) {
            int newSize = backed.length * 2;
            while (newSize < size + addSize) newSize *= 2;
            ary = new float[newSize];
            // copy 0..<index
            System.arraycopy(backed, 0,
                    ary, 0, index);
            backed = ary;
        } else {
            ary = backed;
            // no resize
        }
        // copy index..<size to index+addSize..<size+addSize
        System.arraycopy(backed, index,
                ary, index + addSize, size - index);
        // copy 0..<addSize to index..<index+addSize
        System.arraycopy(c, 0,
                ary, index, addSize);
        size += addSize;
        return true;
    }

    @Override
    public boolean removeAll(Collection<?> c) {
        return batchRemove(c, true);
    }

    @Override
    public boolean retainAll(Collection<?> c) {
        return batchRemove(c, false);
    }

    private boolean batchRemove(Collection<?> c, boolean complement) {
        final float[] data = this.backed;
        int r = 0;
        int w = 0;
        boolean modified = false;
        try {
            if (c instanceof FloatList) {
                FloatList intList = (FloatList) c;
                for (; r < size; r++)
                    if (intList.contains(data[r]) == complement)
                        data[w++] = data[r];
            } else {
                for (; r < size; r++)
                    if (c.contains(data[r]) == complement)
                        data[w++] = data[r];
            }
        } finally {
            // Preserve behavioral compatibility with AbstractCollection,
            // even if c.contains() throws.
            if (r != size) {
                System.arraycopy(data, r,
                        data, w,
                        size - r);
                w += size - r;
            }
            if (w != size) {
                size = w;
                modified = true;
            }
        }
        return modified;
    }

    public final void replaceAll(FloatUnaryOperator operator) {
        Objects.requireNonNull(operator);
        final ListIterator li = this.listIterator();
        while (li.hasNext()) {
            li.set(operator.applyAsFloat(li.nextFloat()));
        }
    }

    @Override
    public void clear() {
        size = 0;
    }

    public final boolean equals(Object o) {
        if (o == this) return true;
        if (!(o instanceof List<?>)) return false;
        if (o instanceof FloatList) {
            if (((FloatList) o).size != size) return false;

            ListIterator e1 = listIterator();
            ListIterator e2 = ((FloatList) o).listIterator();
            while (e1.hasNext() && e2.hasNext()) {
                if (e1.nextFloat() != e2.nextFloat())
                    return false;
            }
            return !(e1.hasNext() || e2.hasNext());
        }

        ListIterator e1 = listIterator();
        java.util.ListIterator<?> e2 = ((List<?>) o).listIterator();
        while (e1.hasNext() && e2.hasNext()) {
            float o1 = e1.nextFloat();
            Object o2 = e2.next();
            if (!eq(o1, o2))
                return false;
        }
        return !(e1.hasNext() || e2.hasNext());
    }

    @Override
    public final int hashCode() {
        int hashCode = 1;
        final ListIterator li = this.listIterator();
        while (li.hasNext())
            hashCode = 31 * hashCode + Float.hashCode(li.nextFloat());
        return hashCode;
    }

    // Positional Access Operations

    public final float getFloat(int index) {
        rangeCheck(index);
        return backed[index];
    }

    /**
     * You should use {@link FloatList#getFloat getFloat}
     */
    @Deprecated
    @Override
    public final Float get(int index) {
        return getFloat(index);
    }

    public float set(int index, float element) {
        rangeCheck(index);
        float r = backed[index];
        backed[index] = element;
        return r;
    }

    /**
     * You should use {@link FloatList#set(int, float)}
     */
    @Deprecated
    @Override
    public final Float set(int index, Float element) {
        return set(index, (float)element);
    }

    public void add(int index, float value) {
        rangeCheckForAdd(index);
        modCount++;
        float[] ary;
        if (backed.length < size + 1) {
            ary = new float[backed.length * 2];
            // copy 0..<index
            System.arraycopy(backed, 0,
                    ary, 0, index);
            backed = ary;
        } else {
            ary = backed;
            // no resize
        }
        // copy index..<size to index+1..<size+1
        System.arraycopy(backed, index,
                ary, index + 1, size - index);
        ary[index] = value;
        size++;
    }

    /**
     * You should use {@link FloatList#add(int, float)}
     */
    @Deprecated
    @Override
    public void add(int index, Float element) {
        add(index, (float)element);
    }

    public float removeAt(int index) {
        rangeCheck(index);
        modCount++;
        float r = backed[index];
        // copy index+1..<size to index..<size-1
        System.arraycopy(backed, index + 1,
                backed, index, size - index - 1);
        size--;
        return r;
    }

    /**
     * You should use {@link FloatList#removeAt removeAt}
     */
    @Deprecated
    @Override
    public Float remove(int index) {
        return removeAt(index);
    }

    /**
     * You should use {@link FloatList#indexOf(float)}
     */
    @Override
    public final int indexOf(Object o) {
        if (!(o instanceof Float)) return -1;
        return indexOf((float)o);
    }

    public final int indexOf(float value) {
        for (int i = 0; i < size; i++) {
            if (value == backed[i]) return i;
        }
        return -1;
    }

    /**
     * You should use {@link FloatList#lastIndexOf(float)}
     */
    @Override
    public final int lastIndexOf(Object o) {
        if (!(o instanceof Float)) return -1;
        return indexOf((float)o);
    }

    public final int lastIndexOf(float value) {
        for (int i = size - 1; i >= 0; i--) {
            if (value == backed[i]) return i;
        }
        return -1;
    }

    // List Iterators

    @Override
    public final ListIterator listIterator() {
        return new ListIterator(0);
    }

    @Override
    public final ListIterator listIterator(int index) {
        rangeCheckForAdd(index);
        return new ListIterator(index);
    }

    public final class ListIterator implements FloatIterator, java.util.ListIterator<Float> {
        int expectedModCount = modCount;
        int lastRet = -1;
        int cursor;

        public ListIterator(int cursor) {
            this.cursor = cursor;
        }

        @Override
        public boolean hasNext() {
            return cursor < size;
        }

        @Override
        public float nextFloat() {
            try {
                checkForComodification();
                int i = cursor;
                float next = getFloat(i);
                lastRet = i;
                cursor = i + 1;
                return next;
            } catch (IndexOutOfBoundsException e) {
                checkForComodification();
                throw new NoSuchElementException();
            }
        }

        @Override
        public Float next() {
            return FloatIterator.super.next();
        }

        public void remove() {
            if (lastRet < 0)
                throw new IllegalStateException();
            checkForComodification();

            try {
                FloatList.this.removeAt(lastRet);
                if (lastRet < cursor)
                    cursor--;
                lastRet = -1;
                expectedModCount = modCount;
            } catch (IndexOutOfBoundsException e) {
                throw new ConcurrentModificationException();
            }
        }

        public boolean hasPrevious() {
            return cursor != 0;
        }

        public float previousFloat() {
            checkForComodification();
            try {
                int i = cursor - 1;
                float previous = getFloat(i);
                lastRet = cursor = i;
                return previous;
            } catch (IndexOutOfBoundsException e) {
                checkForComodification();
                throw new NoSuchElementException();
            }
        }

        public int nextIndex() {
            return cursor;
        }

        public int previousIndex() {
            return cursor-1;
        }

        public void set(float e) {
            if (lastRet < 0)
                throw new IllegalStateException();
            checkForComodification();

            try {
                FloatList.this.set(lastRet, e);
                expectedModCount = modCount;
            } catch (IndexOutOfBoundsException ex) {
                throw new ConcurrentModificationException();
            }
        }

        public void add(float e) {
            checkForComodification();

            try {
                int i = cursor;
                FloatList.this.add(i, e);
                lastRet = -1;
                cursor = i + 1;
                expectedModCount = modCount;
            } catch (IndexOutOfBoundsException ex) {
                throw new ConcurrentModificationException();
            }
        }

        public void set(Float e) {
            set((float)e);
        }
        public void add(Float e) {
            add((float)e);
        }

        public Float previous() {
            return previousFloat();
        }

        private void checkForComodification() {
            if (modCount != expectedModCount)
                throw new ConcurrentModificationException();
        }
    }

    //////////////////////

    private float[] toPrimitives(Collection<? extends Float> c) {
        Float[] wrapper = c.toArray(EMPTY_WRAPPER_ARRAY);
        if (wrapper.length == 0) return EMPTY_PRIMITIVE_ARRAY;
        float[] primitives = new float[wrapper.length];
        for (int i = 0; i < primitives.length; i++) {
            primitives[i] = wrapper[i];
        }
        return primitives;
    }

    private void rangeCheck(int index) {
        if (index < 0 || index >= size())
            throw new IndexOutOfBoundsException(outOfBoundsMsg(index));
    }

    private void rangeCheckForAdd(int index) {
        if (index < 0 || index > size())
            throw new IndexOutOfBoundsException(outOfBoundsMsg(index));
    }

    private String outOfBoundsMsg(int index) {
        return "Index: "+index+", Size: "+size();
    }

    private boolean eq(float o1, Object o2) {
        return o2 instanceof Float && o1 == (float)o2;
    }

    private static final Float[] EMPTY_WRAPPER_ARRAY = new Float[0];
    private static final float[] EMPTY_PRIMITIVE_ARRAY = new float[0];
}
