/*
 * Generated by lists-generator.kts
 */

package com.anatawa12.protobuf;

import java.util.Objects;

@FunctionalInterface
public interface FloatConsumer {
    void accept(float value);

    default FloatConsumer andThen(FloatConsumer after) {
        Objects.requireNonNull(after);
        return (float t) -> { accept(t); after.accept(t); };
    }
}